### ISSUE TITLE
get the full CONLL-X dataset

### ISSUE THREAD

**Issue by jeisner** [karuiwu/reparse#5]
Katherine writes: "It seems that to get data sets in other languages, you will need to request permissions/acquire licenses as mentioned here: http://ilk.uvt.nl/conll/post_task_data.html.  [...] I'd love to able to get the other language datasets."

CLSP is an LDC member, so we are entitled to LDC materials without paying a further fee.

I'll start by asking on the CLSP list if we have this stuff.  If not, I'll ask our sysadmin to get it.

**Comment by junekihong** [comment]
Sounds great. Looking forward to it.

-Juneki and Katherine

**Comment by jeisner** [comment]
On CLSP network, see /export/a10/CoNLL-X .
The README file has important information.
(Remember to ssh to a compute node before doing any real computation; don't use login for that.)
